/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppAbout {}
  interface AppCarousel {}
  interface AppCarouselViewme {
    'type': string;
  }
  interface AppColorpicker {}
  interface AppColorpickerViewme {
    'type': string;
  }
  interface AppColumnchart {}
  interface AppColumnchartViewme {
    'type': string;
  }
  interface AppFlipimages {}
  interface AppFlipimagesViewme {
    'type': string;
  }
  interface AppHome {}
  interface AppHtmltoprint {}
  interface AppHtmltoprintViewme {}
  interface AppLinechart {}
  interface AppLinechartViewme {
    'type': string;
  }
  interface AppRoot {}
  interface AppSlides {}
  interface AppSlidesViewme {
    'type': string;
  }
  interface AppStretchyheader {}
  interface AppStretchyheaderViewme {}
  interface AppSvgmorph {}
  interface AppSvgmorphViewme {
    'type': string;
  }
}

declare global {


  interface HTMLAppAboutElement extends Components.AppAbout, HTMLStencilElement {}
  var HTMLAppAboutElement: {
    prototype: HTMLAppAboutElement;
    new (): HTMLAppAboutElement;
  };

  interface HTMLAppCarouselElement extends Components.AppCarousel, HTMLStencilElement {}
  var HTMLAppCarouselElement: {
    prototype: HTMLAppCarouselElement;
    new (): HTMLAppCarouselElement;
  };

  interface HTMLAppCarouselViewmeElement extends Components.AppCarouselViewme, HTMLStencilElement {}
  var HTMLAppCarouselViewmeElement: {
    prototype: HTMLAppCarouselViewmeElement;
    new (): HTMLAppCarouselViewmeElement;
  };

  interface HTMLAppColorpickerElement extends Components.AppColorpicker, HTMLStencilElement {}
  var HTMLAppColorpickerElement: {
    prototype: HTMLAppColorpickerElement;
    new (): HTMLAppColorpickerElement;
  };

  interface HTMLAppColorpickerViewmeElement extends Components.AppColorpickerViewme, HTMLStencilElement {}
  var HTMLAppColorpickerViewmeElement: {
    prototype: HTMLAppColorpickerViewmeElement;
    new (): HTMLAppColorpickerViewmeElement;
  };

  interface HTMLAppColumnchartElement extends Components.AppColumnchart, HTMLStencilElement {}
  var HTMLAppColumnchartElement: {
    prototype: HTMLAppColumnchartElement;
    new (): HTMLAppColumnchartElement;
  };

  interface HTMLAppColumnchartViewmeElement extends Components.AppColumnchartViewme, HTMLStencilElement {}
  var HTMLAppColumnchartViewmeElement: {
    prototype: HTMLAppColumnchartViewmeElement;
    new (): HTMLAppColumnchartViewmeElement;
  };

  interface HTMLAppFlipimagesElement extends Components.AppFlipimages, HTMLStencilElement {}
  var HTMLAppFlipimagesElement: {
    prototype: HTMLAppFlipimagesElement;
    new (): HTMLAppFlipimagesElement;
  };

  interface HTMLAppFlipimagesViewmeElement extends Components.AppFlipimagesViewme, HTMLStencilElement {}
  var HTMLAppFlipimagesViewmeElement: {
    prototype: HTMLAppFlipimagesViewmeElement;
    new (): HTMLAppFlipimagesViewmeElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppHtmltoprintElement extends Components.AppHtmltoprint, HTMLStencilElement {}
  var HTMLAppHtmltoprintElement: {
    prototype: HTMLAppHtmltoprintElement;
    new (): HTMLAppHtmltoprintElement;
  };

  interface HTMLAppHtmltoprintViewmeElement extends Components.AppHtmltoprintViewme, HTMLStencilElement {}
  var HTMLAppHtmltoprintViewmeElement: {
    prototype: HTMLAppHtmltoprintViewmeElement;
    new (): HTMLAppHtmltoprintViewmeElement;
  };

  interface HTMLAppLinechartElement extends Components.AppLinechart, HTMLStencilElement {}
  var HTMLAppLinechartElement: {
    prototype: HTMLAppLinechartElement;
    new (): HTMLAppLinechartElement;
  };

  interface HTMLAppLinechartViewmeElement extends Components.AppLinechartViewme, HTMLStencilElement {}
  var HTMLAppLinechartViewmeElement: {
    prototype: HTMLAppLinechartViewmeElement;
    new (): HTMLAppLinechartViewmeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppSlidesElement extends Components.AppSlides, HTMLStencilElement {}
  var HTMLAppSlidesElement: {
    prototype: HTMLAppSlidesElement;
    new (): HTMLAppSlidesElement;
  };

  interface HTMLAppSlidesViewmeElement extends Components.AppSlidesViewme, HTMLStencilElement {}
  var HTMLAppSlidesViewmeElement: {
    prototype: HTMLAppSlidesViewmeElement;
    new (): HTMLAppSlidesViewmeElement;
  };

  interface HTMLAppStretchyheaderElement extends Components.AppStretchyheader, HTMLStencilElement {}
  var HTMLAppStretchyheaderElement: {
    prototype: HTMLAppStretchyheaderElement;
    new (): HTMLAppStretchyheaderElement;
  };

  interface HTMLAppStretchyheaderViewmeElement extends Components.AppStretchyheaderViewme, HTMLStencilElement {}
  var HTMLAppStretchyheaderViewmeElement: {
    prototype: HTMLAppStretchyheaderViewmeElement;
    new (): HTMLAppStretchyheaderViewmeElement;
  };

  interface HTMLAppSvgmorphElement extends Components.AppSvgmorph, HTMLStencilElement {}
  var HTMLAppSvgmorphElement: {
    prototype: HTMLAppSvgmorphElement;
    new (): HTMLAppSvgmorphElement;
  };

  interface HTMLAppSvgmorphViewmeElement extends Components.AppSvgmorphViewme, HTMLStencilElement {}
  var HTMLAppSvgmorphViewmeElement: {
    prototype: HTMLAppSvgmorphViewmeElement;
    new (): HTMLAppSvgmorphViewmeElement;
  };
  interface HTMLElementTagNameMap {
    'app-about': HTMLAppAboutElement;
    'app-carousel': HTMLAppCarouselElement;
    'app-carousel-viewme': HTMLAppCarouselViewmeElement;
    'app-colorpicker': HTMLAppColorpickerElement;
    'app-colorpicker-viewme': HTMLAppColorpickerViewmeElement;
    'app-columnchart': HTMLAppColumnchartElement;
    'app-columnchart-viewme': HTMLAppColumnchartViewmeElement;
    'app-flipimages': HTMLAppFlipimagesElement;
    'app-flipimages-viewme': HTMLAppFlipimagesViewmeElement;
    'app-home': HTMLAppHomeElement;
    'app-htmltoprint': HTMLAppHtmltoprintElement;
    'app-htmltoprint-viewme': HTMLAppHtmltoprintViewmeElement;
    'app-linechart': HTMLAppLinechartElement;
    'app-linechart-viewme': HTMLAppLinechartViewmeElement;
    'app-root': HTMLAppRootElement;
    'app-slides': HTMLAppSlidesElement;
    'app-slides-viewme': HTMLAppSlidesViewmeElement;
    'app-stretchyheader': HTMLAppStretchyheaderElement;
    'app-stretchyheader-viewme': HTMLAppStretchyheaderViewmeElement;
    'app-svgmorph': HTMLAppSvgmorphElement;
    'app-svgmorph-viewme': HTMLAppSvgmorphViewmeElement;
  }
}

declare namespace LocalJSX {
  interface AppAbout {}
  interface AppCarousel {}
  interface AppCarouselViewme {
    'type'?: string;
  }
  interface AppColorpicker {}
  interface AppColorpickerViewme {
    'type'?: string;
  }
  interface AppColumnchart {}
  interface AppColumnchartViewme {
    'type'?: string;
  }
  interface AppFlipimages {}
  interface AppFlipimagesViewme {
    'type'?: string;
  }
  interface AppHome {}
  interface AppHtmltoprint {}
  interface AppHtmltoprintViewme {}
  interface AppLinechart {}
  interface AppLinechartViewme {
    'type'?: string;
  }
  interface AppRoot {}
  interface AppSlides {}
  interface AppSlidesViewme {
    'type'?: string;
  }
  interface AppStretchyheader {}
  interface AppStretchyheaderViewme {}
  interface AppSvgmorph {}
  interface AppSvgmorphViewme {
    'type'?: string;
  }

  interface IntrinsicElements {
    'app-about': AppAbout;
    'app-carousel': AppCarousel;
    'app-carousel-viewme': AppCarouselViewme;
    'app-colorpicker': AppColorpicker;
    'app-colorpicker-viewme': AppColorpickerViewme;
    'app-columnchart': AppColumnchart;
    'app-columnchart-viewme': AppColumnchartViewme;
    'app-flipimages': AppFlipimages;
    'app-flipimages-viewme': AppFlipimagesViewme;
    'app-home': AppHome;
    'app-htmltoprint': AppHtmltoprint;
    'app-htmltoprint-viewme': AppHtmltoprintViewme;
    'app-linechart': AppLinechart;
    'app-linechart-viewme': AppLinechartViewme;
    'app-root': AppRoot;
    'app-slides': AppSlides;
    'app-slides-viewme': AppSlidesViewme;
    'app-stretchyheader': AppStretchyheader;
    'app-stretchyheader-viewme': AppStretchyheaderViewme;
    'app-svgmorph': AppSvgmorph;
    'app-svgmorph-viewme': AppSvgmorphViewme;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-about': LocalJSX.AppAbout & JSXBase.HTMLAttributes<HTMLAppAboutElement>;
      'app-carousel': LocalJSX.AppCarousel & JSXBase.HTMLAttributes<HTMLAppCarouselElement>;
      'app-carousel-viewme': LocalJSX.AppCarouselViewme & JSXBase.HTMLAttributes<HTMLAppCarouselViewmeElement>;
      'app-colorpicker': LocalJSX.AppColorpicker & JSXBase.HTMLAttributes<HTMLAppColorpickerElement>;
      'app-colorpicker-viewme': LocalJSX.AppColorpickerViewme & JSXBase.HTMLAttributes<HTMLAppColorpickerViewmeElement>;
      'app-columnchart': LocalJSX.AppColumnchart & JSXBase.HTMLAttributes<HTMLAppColumnchartElement>;
      'app-columnchart-viewme': LocalJSX.AppColumnchartViewme & JSXBase.HTMLAttributes<HTMLAppColumnchartViewmeElement>;
      'app-flipimages': LocalJSX.AppFlipimages & JSXBase.HTMLAttributes<HTMLAppFlipimagesElement>;
      'app-flipimages-viewme': LocalJSX.AppFlipimagesViewme & JSXBase.HTMLAttributes<HTMLAppFlipimagesViewmeElement>;
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-htmltoprint': LocalJSX.AppHtmltoprint & JSXBase.HTMLAttributes<HTMLAppHtmltoprintElement>;
      'app-htmltoprint-viewme': LocalJSX.AppHtmltoprintViewme & JSXBase.HTMLAttributes<HTMLAppHtmltoprintViewmeElement>;
      'app-linechart': LocalJSX.AppLinechart & JSXBase.HTMLAttributes<HTMLAppLinechartElement>;
      'app-linechart-viewme': LocalJSX.AppLinechartViewme & JSXBase.HTMLAttributes<HTMLAppLinechartViewmeElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'app-slides': LocalJSX.AppSlides & JSXBase.HTMLAttributes<HTMLAppSlidesElement>;
      'app-slides-viewme': LocalJSX.AppSlidesViewme & JSXBase.HTMLAttributes<HTMLAppSlidesViewmeElement>;
      'app-stretchyheader': LocalJSX.AppStretchyheader & JSXBase.HTMLAttributes<HTMLAppStretchyheaderElement>;
      'app-stretchyheader-viewme': LocalJSX.AppStretchyheaderViewme & JSXBase.HTMLAttributes<HTMLAppStretchyheaderViewmeElement>;
      'app-svgmorph': LocalJSX.AppSvgmorph & JSXBase.HTMLAttributes<HTMLAppSvgmorphElement>;
      'app-svgmorph-viewme': LocalJSX.AppSvgmorphViewme & JSXBase.HTMLAttributes<HTMLAppSvgmorphViewmeElement>;
    }
  }
}


